### ISSUE TITLE
Embedding of linked items in Rich Text Fields limited to img only

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-content-management#13]
DXA has a nice method to 'embed' linked items in Rich Text fields, by expanding the linked item into a separate RTF fragment containing full linked entity JSON. This allows for custom handling of the embedded item within the web application (for example to render a fancy video player, or responsive images). For the moment it is limited to content which is linked using an `<img>` element, however I have a couple of use cases where I would like an embedded linked item, which is not an image:

1. Downloads - we want to enrich RTF links to downloads (PDFs etc.) with the file size and icon for file type
2. Tooltips - we want to be able to create links to tooltip components (a normal component containing help text), which show help text in a tooltip on the page when the link is clicked.

As the logic to embed already exists, it would be great if this was made more generic and configurable, so for example you could specify a TBB parameter with a list of schema names for which linked RTF content should be embedded.

https://github.com/sdl/dxa-content-management/blob/25873210b246ab397dfc8efd0b63f30e1c5243f1/Sdl.Web.Tridion.Templates.R2/Data/DataModelBuilder.cs#L290

**Comment by willprice76** [comment]
I'm working on a Pull Request for this, but unfortunately it seems like there is also a bug in the Java web application which means that embedded entities in Rich Text (including images) just don't work. Will add an issue and hopefully a fix this too in the next days!

**Comment by willprice76** [comment]
This also needs to be fixed: https://github.com/sdl/dxa-web-application-java/issues/93

**Comment by willprice76** [comment]
Here is the code change for the .NET web application
https://github.com/sdl/dxa-web-application-dotnet/issues/65 
These 3 PRs related to these issues together constitute resolution for this issue on CM + Web Java + Web .NET

**Comment by rpannekoek** [comment]
Internal ID (for tracking purposes): CRQ-12781

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
