### ISSUE TITLE
HtmlClasses property only set for EntityModelData and not PageModelData

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-content-management#14]
Since our upgrade to DXA 2.0 (from 1.8) we notice that the htmlClasses metadata on the Page Template no longer is available in our (Java) web application `PageModel.htmlClasses` property. For Entities we can see that the template metadata is put on the Entity model at publish time in the `DefaultModelBuilder.BuildEntityModel `method:

https://github.com/sdl/dxa-content-management/blob/25873210b246ab397dfc8efd0b63f30e1c5243f1/Sdl.Web.Tridion.Templates.R2/Data/DefaultModelBuilder.cs#L171

The same mechanism should be applied during the BuildPageModel method.

**Comment by majiccode** [comment]
Internal issue for tracking purposes: https://jira.sdl.com/browse/TSI-3169

**Comment by rpannekoek** [comment]
Fixed in DXA 2.1
