### ISSUE TITLE
Navigation items don't get title from Structure Group metadata

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-content-management#17]
Currently the title in the navigation.json (which is used to build menus and breadcrumbs) always comes from the structure group title. This means you have to change the title of the structure group in order to localize the navigation, which can become confusing for editors, who may not understand which structure group is what in languages which they cannot understand. It would be great if the navigation title could come from a metadata field instead, and that which fields were processed worked in the same way as for finding the title from a page in the first component on the page.

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
