### ISSUE TITLE
Empty embedded schema field value can result in empty string in model JSON

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-content-management#19]
We have schemas which use a common Standard Metadata embedded schema for metadata field values. If there is no content in this embedded field, then the published entity model JSON has, instead of no, or null value an empty string value. This then causes errors in the model mapping in the (Java) web application, as it tries to map a string value to an object.

**Comment by rpannekoek** [comment]
This has been fixed in https://github.com/sdl/dxa-content-management/releases/tag/DXA_2.2.1_Hotfix
