### ISSUE TITLE
Not easy to exclude core module when installing/upgrading

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-content-management#24]
NOTE: This issue is actually related to the installation/upgrade scripts for DXA, but as this codebase is not on Github, I am adding the issue in this repo.

The DXA comes with a Core module, with example schemas and templates used to build the example website. This is a useful reference, but many DXA implementation will not make use of these and they will normally be deleted to prevent them being accidentally used, or confused with similarly named items in the customer's implementation.

The problem is, that when running upgrade scripts, these schemas and templates will be imported again into the CMS, and thus need to be deleted again (which is a painstaking process due to the interdependency of items). The other option is to use content porter to handpick only the framework items to import, but this is error prone and also has dependency problems (see https://tridion.stackexchange.com/a/18575/54)

It would be great if there was a further install/upgrade option "framework-only" which only imports the DXA framework and not the core module.

**Comment by rpannekoek** [comment]
This feature has been added to DXA 2.1 (although it seems DXA 2.1 Docs should still be updated).  Furthermore, DXA 2.1 is .NET only. Keeping this one open for a while.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-13026

**Comment by rpannekoek** [comment]
In DXA 2.1, this feature only works in upgrade scenarios.  The plan is to make it work in new install scenarios too in DXA 2.2.

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
