### ISSUE TITLE
Sitemap can contain non-published pages

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-content-management#29]
If you have pages which are shared across sites, or publications within a single site, as soon as the page is published in one publication, it will appear in the sitemap of all publications where it is shared. This is due to a bug in the templating logic (GenerateSitemap TBB):

https://github.com/sdl/dxa-content-management/blob/da4925df268846b16bb29d431383e8728743633e/Sdl.Web.Tridion.Templates/Templates/GenerateSitemap.cs#L254

The call in the IsPublished method to PublishEngine.IsPublished omits the optional third parameter (bool isPublishedInContext) which means that it returns true whenever the page is published from *any* publication, rather than just the context publication

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12798

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
