### ISSUE TITLE
DXA Resolver - not publishing the DCP component if we publishing with Structure Group

### ISSUE THREAD

**Issue by avmgan** [sdl/dxa-content-management#32]
I have tested this DXA Resolver in  Sites 9.0 and DXA 2.1, Publishing the Structure Group DCP components is not getting auto published, It's only getting published if we publish by page.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12797

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
