### ISSUE TITLE
DXA Resolver error when multiple components link to same component

### ISSUE THREAD

**Issue by jsuurd** [sdl/dxa-content-management#35]
When testing DXA 2.0 Example Site it appears the DXA Resolver behaves inconsistently.

For instance when publishing the 'Sitemap' page, the 'Sitemap' article DCP is resolved and published. This can be validated by viewing the 'Show Items to Publish' in the publish dialog.

However when publishing the '000 Home' page, the 'Homepage Welcome' article is not resolved or published. When validated by viewing the 'Show Items to Publish' in the publish dialog, the 'Homepage Welcome' article is not shown.

After some investigation it turns out the DXA Resolver throws an error when two components on the page link to the same component (i.e. on the '000 Home' page both the 'Homepage List' and 'Latest News' components link to the same 'News Intro' component). In this case the DXA Rresolver throws the following error: 

    Gathering linked components for component Latest News
    Exception occured: An item with the same key has already been added.
    Stacktrace:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Sdl.Web.DXAResolver.Resolver.ResolveItem(IdentifiableObject item, ComponentTemplate template, HashSet`1 resolved, Int32 recurseLevel)
       at Sdl.Web.DXAResolver.Resolver.Resolve(IdentifiableObject item, ResolveInstruction instruction, PublishContext context, ISet`1 resolvedItems)

**Comment by mborysenko** [comment]
Internal Issue ID (for tracking purposes): CRQ-13673

**Comment by rpannekoek** [comment]
Thianks for reporting this issue!

This issue has already been found an fixed earlier: 
https://github.com/sdl/dxa-content-management/commit/0a7b6d9b8716755f2fe1ad7b514edbb7da42c71e

The fix is in DXA 2.1  and also merged to the `release/2.0` branch, so you will have it if you build from that branch yourself.

We are also planning release the compiled 2.0 hotfix on GitHub.

**Comment by rpannekoek** [comment]
A fix for this issue is available in DXA 2.1+ and also in the [DXA 2.0.1 hotfix release](https://github.com/sdl/dxa-content-management/releases/tag/DXA_2.0.1_Hotfix)
