### ISSUE TITLE
Empty optional embedded fields result in error when parent field is mandatory

### ISSUE THREAD

**Issue by jsuurd** [sdl/dxa-content-management#36]
When a schema contains an embedded schema field that is mandatory and all fields of the embedded schema are optional (a debatable schema design, but reality at the client) and all optional fields are empty, the 'Render Component Content' TBB throws the following error:

```
Object cannot be stored in an array of this type.
at System.Array.InternalSetValue(Void* target, Object value)
at System.Array.SetValue(Object value, Int32 index)
at Sdl.Web.Tridion.Templates.R2.Data.DataModelBuilder.GetTypedArrayOfValues[T](List1 fieldValues)
at Sdl.Web.Tridion.Templates.R2.Data.DataModelBuilder.BuildContentModel(XmlElement xmlElement, Int32 expandLinkDepth)
```

In the source tab of the component the following XML would be generated. Note the empty MandatoryEmbeddedSchemaField node for the field where all optional fields are empty:

```
<MyComponent>
	<MandatoryEmbeddedSchemaField>
		<OptionalField>Field value</OptionalField>
	</MandatoryEmbeddedSchemaField>
	<MandatoryEmbeddedSchemaField></MandatoryEmbeddedSchemaField>
</MyComponent>
```

**Comment by rpannekoek** [comment]
Similar problem as reported here: https://github.com/sdl/dxa-content-management/issues/19
It seems that the (PR for that issue)[https://github.com/sdl/dxa-content-management/pull/20] can also fix this. Please confirm.

**Comment by rpannekoek** [comment]
This has been fixed in https://github.com/sdl/dxa-content-management/releases/tag/DXA_2.2.1_Hotfix
