### ISSUE TITLE
Rendering of multivalue RTF fields may result in wrong model type in JSON

### ISSUE THREAD

**Issue by jsuurd** [sdl/dxa-content-management#39]
Rendering of multivalue RTF fields may result in wrong model type in JSON. This issue was introduced in PR #22 and is described in more detail on [Tridion StackExchange](https://tridion.stackexchange.com/questions/18986/org-springframework-http-converter-httpmessagenotreadableexception-could-not-re):

> OK, the JSON fragment reveals the problem: the "$type": "List``1" is not expected (it should be "$type": "RichTextData[]"); you can see that in the exception message: "ModelDataTypeIdResolver - Found id = List`1 which we don't know".

**Comment by rpannekoek** [comment]
This issue was already fixed earlier, but the fix was not merged to release/2.0 branch. This has been done now and the fix is also included in the DXA 2.2.1 hotfix release: https://github.com/sdl/dxa-content-management/releases/tag/DXA_2.2.1_Hotfix
