### ISSUE TITLE
Post build Event _references folder

### ISSUE THREAD

**Issue by rajesh3200** [sdl/dxa-content-management#5]
Can we update the POST build event to use the below script. 

"C:\Program Files (x86)\Microsoft\ILMerge\ILMerge.exe"  ^    /out:Sdl.Web.Tridion.Templates.merged.dll ^    /targetplatform:v4 ^    /lib:%Tridion_Home%\bin\client ^    /lib:%Tridion_Home%\bin\client\TopologyManager ^    Sdl.Web.Tridion.Templates.dll DD4T.ContentModel.Contracts.dll DD4T.ContentModel.dll DD4T.Serialization.dll DD4T.Templates.Base.dll Newtonsoft.Json.dll

In this way users does not have to create those _references folders manually and build the project without copying the dll's.

**Comment by rpannekoek** [comment]
The `_references` subfolders are not only used in the post build event, but also as hintpaths in the project's References.
Furthermore, for backwards compatibility reasons, we use some reference assemblies from 2013 SP1.
Expecting the reference assemblies in :`%TRIDION_HOME%\bin\client` is indeed convenient if (and only if) you build on a CM server, but it won't give you the right version mix we need for backward compatibility purposes.

Of course, you're free to modify this locally if you have to do a custom build of the `Sdl.Web.Tridion.Templates`.
