### ISSUE TITLE
cms-import.ps1 publication mapping

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-content-management#6]
As a developer I would like to be able to provide a publication mapping to the cms-import.ps1 script. This is used to instruct the script to import the content in other-than-default publications.

I.e. "200 Example Content" -> "200 Global Content"
and maybe even "110 DXA Site Type" -> "100 Master" for an implementation which does not use site types.

This is especially useful when doing an DXA upgrade: chances are that publication names have been changed.

The workaround is to rename the publications to the original publication name DXA is using, run the import, and change the publication names back again.

**Comment by rpannekoek** [comment]
It is already possible to do publication title mapping when doing `master-only` import (and when importing DXA Modules).
Unfortunately, publication title mapping currently doesn't work for `all-publications` or `example-publication`. This is due to a limitation (bug) in the CM Import Service.

**Comment by rpannekoek** [comment]
Unable to implement this due to a limitation in the CM Import.
